name: Build binary release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build_arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: pguyot/arm-runner-action@v2
      id: build_image
      with:
        base_image: raspios_lite_arm64:latest
        commands: |
            git clone --depth=1 ${{ github.server_url }}/${{ github.repository }}.git
            cd ${{ github.event.repository.name }}
