name: Build binary release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build_windows64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up latest Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Get dependencies
      run: |
        pip install -r requirements.txt

    - name: Inject build string
      run: |
        py .github/workflows/inject_buildstr.py app.py
        py .github/workflows/inject_buildstr.py BEAMinjector.py

    - name: Build BEAMinject
      run: |
        pip install nuitka
        echo `n | py -m nuitka --onefile --enable-plugin=tk-inter --include-package=customtkinter --disable-console app.py
        py -m nuitka --onefile --disable-console BEAMinjector.py

    - name: Pack files with UPX
      run: |
        pip install requests
        py .github/workflows/get_upx.py -nf win64 .
        mv BEAMinjector.exe BEAMinject.exe
        ./upx --brute BEAMinject.exe
        mv app.exe BEAMinject_GUI.exe
        ./upx --brute BEAMinject_GUI.exe

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: BEAMinject_nightly
        path: |
          D:\a\BEAMinject\BEAMinject\BEAMinject.exe
          D:\a\BEAMinject\BEAMinject\BEAMinject_GUI.exe
