name: Build binary release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build_windows64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up latest Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Compile Pyinstaller & install
      run: |
        git clone https://github.com/pyinstaller/pyinstaller.git
        cd pyinstaller/bootloader
        py waf all
        cd ..
        pip install .

    - name: Get dependencies
      run: |
        pip install -r requirements.txt
        pip install requests
        py .github/workflows/get_upx.py -nf win64 .

    - name: Build binary
      run: |
        # For easily debuggable builds
        py ./.github/workflows/inject_buildstr.py app.py
        py ./.github/workflows/inject_buildstr.py BEAMinjector.py

        py -m PyInstaller --add-data="getmc.ps1:." --noconsole --onefile BEAMinjector.py
        mv dist/BEAMinjector.exe BEAMinject.exe
        py -m PyInstaller --add-data="getmc.ps1:." --noconsole --onefile app.py
        mv dist/app.exe BEAMinject_GUI.exe

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: BEAMinject_nightly
        path: |
          D:\a\BEAMinject\BEAMinject\BEAMinject.exe
          D:\a\BEAMinject\BEAMinject\BEAMinject_GUI.exe
